#!/bin/bash

#####################################################
#					Cleanup Script					#
#				Version 2022-rev 1.1 				#
#    https://github.com/drpoutine/unraid_rclone/    #
#####################################################

echo "$(date "+%d.%m.%Y %T") INFO: *** Starting rclone_cleanup script ***"

####### Cleanup Tracking Files #######

echo "$(date "+%d.%m.%Y %T") INFO: *** Removing Tracking Files ***"

find /mnt/user/appdata/rclone/remotes -name dockers_started* -delete
find /mnt/user/appdata/rclone/remotes -name mount_running* -delete
find /mnt/user/appdata/rclone/remotes -name upload_running* -delete
echo "$(date "+%d.%m.%Y %T") INFO: ***Finished Cleanup! ***"

exit
